1. Create a numpy array with numpy.array module and with a data type integer and float.
2. Create numpy arrays that have zero, one, two, three, Four dimensions respectively. Also, print the shape and dimensions of the numpy arrays created above.
3. Create a 2x3, 3x3, and 4x4 identity matrix using numpy.
4. Create a numpy array with shape 2x5 that has all the elements as zero.
5. Create a numpy array that has the shape 3x5 and all the elements are 5.
6. Create a numpy array with random integers in the range 0-100, and the sample size should be 25.
7. Create a numpy array with a shape 3x3 that has all elements as 1.
8. Create a numpy array in the shape 2x3 with random integers in the range 0-100. Reshape the array in the shape 3x2 and print the updated shape of the resultant array.
9. Create a random array, with the range 0-1000, with a size 50 and step 2. Perform the following operations on the same. a. Print the first ten elements of the array. b. Print the last ten elements of the array c. Print
the elements from the indexes 10-25 d. Print the element at the index 22 e. Print the array using negative indexing. f. Print the last ten elements of the array, using negative indexing.
10. Given a numpy array that has values = [1,2,3,4,5]. Perform the following operations. a. Insert the element 6 at the end of the array. b. Insert the element 10 at the beginning of the array. c. Insert the element 30,
before 4. d. Update the element 5 as 50. e. Delete the element 50 in the updated array. f. Create a function to search for the element 30. g. Sort the array in ascending order.


Create a numpy array with numpy.array module and with a data type integer and float.

In [1]:
import numpy as np


integer_array = np.array([1, 2, 3, 4, 5], dtype=int)


float_array = np.array([1.1, 2.2, 3.3, 4.4, 5.5], dtype=float)

print("Integer Array:")
print(integer_array)
print("Float Array:")
print(float_array)


Integer Array:
[1 2 3 4 5]
Float Array:
[1.1 2.2 3.3 4.4 5.5]


Create numpy arrays that have zero, one, two, three, Four dimensions respectively. Also, print the shape and dimensions of the numpy arrays created above.

In [2]:
a=np.array(1)

In [3]:
a.ndim

0

In [4]:
b=np.array ([1,2,3,4])
b.ndim

1

In [5]:
b=np.array ([1,2,3,4],ndmin=2)
b.ndim

2

In [6]:
b=np.array ([1,2,3,4],ndmin=3)
b.ndim

3

In [7]:
b=np.array ([1,2,3,4],ndmin=4)
b.ndim

4

In [8]:
a=np.random.randint(10)
b=np.random.randint(10,20 , size =(2,4))
c=np.random.randint(10,20 , size =(2,4,2))


In [12]:
b.ndim

2

In [14]:
c.ndim

3

In [15]:
b

array([[16, 11, 16, 17],
       [18, 15, 10, 11]])

Create a 2x2, 3x3, and 4x4 identity matrix using numpy.

In [16]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [17]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.diag([1,1,1])


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])


Create a numpy array with shape 2x5 that has all the elements as zero.

In [21]:
np.zeros((2,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Create a numpy array that has the shape 3x5 and all the elements are 5.

In [22]:
np.full((3, 5), 5)


array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

Create a numpy array with random integers in the range 0-100, and the sample size should be 25.

In [24]:
np.random.randint(0, 101, 25)


array([ 50,  31,  27,  75,  80,  58,  31,  85,   5,  84,   3, 100,  47,
        73,  81,  91,  31,  42,  20,  28,  20,  65,  79,  60,  39])

Create a numpy array with a shape 3x3 that has all elements as 1.

In [25]:
 np.full((3, 3), 1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

Create a numpy array in the shape 2x3 with random integers in the range 0-100. Reshape the array in the shape 3x2 and print the updated shape of the resultant array.

In [27]:
a=np.random.randint(0, 101,size = (2,3))
a=a.reshape(3,2)
print(a)


[[14 36]
 [64 70]
 [95 89]]


Create a random array, with the range 0-1000, with a size 50 and step 2. Perform the following operations on the same. a. Print the first ten elements of the array. b. Print the last ten elements of the array c. Print the elements from the indexes 10-25 d. Print the element at the index 22 e. Print the array using negative indexing. f. Print the last ten elements of the array, using negative indexing.

In [39]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
a=a[::2]
print(a[0:11])
print(a[-11:])
print(a[5:8])
print(a[5])
print(a[-16:])


[ 1  3  5  7  9 11 13 15]
[ 1  3  5  7  9 11 13 15]
[11 13 15]
11
[ 1  3  5  7  9 11 13 15]


In [48]:
a=np.random.randint(0, 1001,100)
a

array([111,  12, 535, 245, 876, 897,  10,  82, 405,  38,  66, 450, 115,
       544, 413, 926, 868, 566, 630, 824, 400,  73, 623, 450, 122, 791,
       176,  14,  71, 797,  41, 939,  51, 943, 898, 679,  62, 777, 133,
       350, 852, 152, 438, 715, 486, 495, 719, 664, 454, 127, 794,  39,
       752, 200,  24, 949, 686, 390, 852,  24, 547,  65, 591, 890,  10,
       741, 630, 870, 967, 865, 277, 277, 574, 685, 928, 309, 438, 217,
       478, 177, 503, 730, 805, 351,  39, 974, 831, 908, 693, 994, 316,
       106, 702, 366, 663, 720, 272, 260, 971, 302])

In [49]:
a=a[::2]

In [50]:
a

array([111, 535, 876,  10, 405,  66, 115, 413, 868, 630, 400, 623, 122,
       176,  71,  41,  51, 898,  62, 133, 852, 438, 486, 719, 454, 794,
       752,  24, 686, 852, 547, 591,  10, 630, 967, 277, 574, 928, 438,
       478, 503, 805,  39, 831, 693, 316, 702, 663, 272, 971])


Given a numpy array that has values = [1,2,3,4,5]. Perform the following operations. a. Insert the element 6 at the end of the array. b. Insert the element 10 at the beginning of the array. c. Insert the element 30, before 4. d. Update the element 5 as 50. e. Delete the element 50 in the updated array. f. Create a function to search for the element 30. g. Sort the array in ascending order.

In [69]:
a=np.array([1,2,3,4,5])
# append
a=np.append(a,6)

In [70]:
a

array([1, 2, 3, 4, 5, 6])

In [71]:
np.insert(a,0,10)

array([10,  1,  2,  3,  4,  5,  6])

In [72]:
np.insert(a,3,30)

array([ 1,  2,  3, 30,  4,  5,  6])

In [73]:
x=list(a)
x

[1, 2, 3, 4, 5, 6]

In [74]:
x.index(4)

3

In [75]:
a[4]=50
a

array([ 1,  2,  3,  4, 50,  6])

In [76]:
np.delete(a,4)

array([1, 2, 3, 4, 6])

In [97]:
def search(arr,elem):
    for k in arr:
        if k==elem:
            return True;
    return False;
search(a,40)

False

Given two numpy arrays A and B that have values [1,2,3,4] and [5,6,7,8] respectively.
Perform the following operations.
a. Add the two arrays
b. Subtract the two arrays
c. Multiply the two arrays:
i. With 5
ii. With each other.
d. Divide the two arrays:
i. By 2
ii. Divide A with B
iii. Divide B with A.

In [99]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
add_arr = a + b
print(add_arr)
sub_arr = a - b
print(sub_arr)
mul_arr = a * b
print(mul_arr)


[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]


In [100]:
arr1 = [1,2,3,4]
arr2 = [5,6,7,8]
print(np.add(arr1,arr2))
print(np.subtract(arr1,arr2))
print(np.multiply(arr1,5))
print(np.multiply(arr1,arr2))
print(np.divide(arr1,2))
print(np.divide(arr1,arr2))


[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 10 15 20]
[ 5 12 21 32]
[0.5 1.  1.5 2. ]
[0.2        0.33333333 0.42857143 0.5       ]


For the given two arrays A and B.
a = np.array([[2,9],[6,13]])
b = np.array([[1,4],[3,11]])
Perform the following operations,
a. Cross product of A and B.
b. Dot product of A and B.
c. Matrix multiplication of A and B.
d. Square root of A and B.

In [101]:
a = np.array([[2,9] , [6,13]])
b = np.array([[1,4] , [3,11]])

#Cross prod of a and b
print(f'Cross Prod of a and b : ', np.cross(a,b))

#Dot prod of a and b
print(f'Cross Prod of a and b : ', np.dot(a,b))


Cross Prod of a and b :  [-1 27]
Cross Prod of a and b :  [[ 29 107]
 [ 45 167]]


In [102]:
print(np.multiply(a,b))
print(np.sqrt(a))


[[  2  36]
 [ 18 143]]
[[1.41421356 3.        ]
 [2.44948974 3.60555128]]


In [104]:
np.matmul(a,b)

array([[ 29, 107],
       [ 45, 167]])